Fixes Mac build error where it's missing proper sys/types.h
```
In file included from external/boringssl/src/crypto/cpu_aarch64_apple.c:20:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/sysctl.h:83:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/sys/ucred.h:101:2: error: unknown type name 'u_int'
        u_int   cr_version;             /* structure layout version */
        ^
```

limits -D_XOPEN_SOURCE=700 to the android target.

https://boringssl.googlesource.com/boringssl/+/1e15682f1a4bb64c48b84884976a2b5c4201e878

Test: Mac builds

Change-Id: Ie8c17fc3d6095eeaea90288151e112a709e444d1